import os
import json
from typing import Optional, List, Dict, Any
from fastapi import FastAPI, UploadFile, File, HTTPException, Query
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import uvicorn
from openai import OpenAI

from analytics import ConfigAnalyticsEngine

app = FastAPI(title="ConfigIntel Observability API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize OpenRouter Client
openrouter_api_key = os.environ.get("OPENROUTER_API_KEY")
or_client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=openrouter_api_key,
) if openrouter_api_key else None

class CopilotChatRequest(BaseModel):
    query: str
    mode: Optional[str] = "Gemini"
    gemini_key: Optional[str] = None

class CopilotSummaryRequest(BaseModel):
    query: Optional[str] = ""
    mode: Optional[str] = "Gemini"
    gemini_key: Optional[str] = None

# Backwards compatibility alias
ChatRequest = CopilotChatRequest

# Initialize engine with default datasets if available on disk
engine = ConfigAnalyticsEngine(
    csv_path="execution_data_master.csv", 
    jsonl_path="system_execution_logs.jsonl"
)

@app.get("/api/health")
async def health_check():
    """Health and status endpoint for frontend connection verification."""
    return {
        "status": "healthy",
        "data_loaded": not engine.df.empty,
        "total_runs": len(engine.df) if not engine.df.empty else 0,
        "columns": list(engine.df.columns)[:15] if not engine.df.empty else []
    }

@app.post("/api/ingest")
async def ingest_data(csv_file: UploadFile = File(...), jsonl_file: Optional[UploadFile] = File(None)):
    """Ingests fresh CSV telemetry and optional JSONL trace logs."""
    try:
        jsonl_lines = None
        if jsonl_file and jsonl_file.filename:
            content = await jsonl_file.read()
            jsonl_lines = content.splitlines()
            
        csv_file.file.seek(0)
        engine.update_from_memory(csv_file.file, jsonl_lines)
        return {
            "status": "success", 
            "total_runs": len(engine.df),
            "message": f"Successfully ingested {len(engine.df):,} execution runs."
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Ingestion failed: {str(e)}")

@app.get("/api/dashboard")
async def get_dashboard():
    """Returns aggregated KPIs, SHAP metrics, and Pareto frontier."""
    data = engine.get_dashboard_data()
    if not data:
        raise HTTPException(status_code=400, detail="No dataset loaded. Please ingest data.")
    return data

@app.get("/api/runs")
async def get_runs(
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    status: Optional[str] = Query(None),
    search: Optional[str] = Query(None)
):
    """Returns paginated and searchable runs for the live trace explorer."""
    return engine.get_runs_list(limit=limit, offset=offset, status=status, search=search)

@app.get("/api/run/{run_id}")
async def get_single_run(run_id: str):
    """Returns details and full trace events for a specific run ID."""
    details, logs = engine.get_run_details(run_id)
    if not details:
        raise HTTPException(status_code=404, detail=f"Run {run_id} not found.")
    return {"run_id": run_id, "details": details, "events": logs}

@app.get("/api/diff")
async def get_diff(pass_id: str, fail_id: str):
    """Calculates configuration and trace log diff between passing and failing executions."""
    if engine.df.empty:
        raise HTTPException(status_code=400, detail="No dataset loaded in engine.")
    params, log_p, log_f = engine.compute_run_diff(pass_id, fail_id, as_df=False)
    return {"params": params, "log_p": log_p, "log_f": log_f}

@app.get("/api/chart/xgboost")
async def get_xgboost_chart():
    """Returns direct PNG generated by XGBoost."""
    for folder in ["frontend/public", "public", "."]:
        p = os.path.join(folder, "xgboost_importance.png")
        if os.path.exists(p):
            return FileResponse(p, media_type="image/png")
    engine.generate_plots("frontend/public")
    for folder in ["frontend/public", "public", "."]:
        p = os.path.join(folder, "xgboost_importance.png")
        if os.path.exists(p):
            return FileResponse(p, media_type="image/png")
    raise HTTPException(status_code=404, detail="Chart not found")

@app.get("/api/chart/shap")
async def get_shap_chart():
    """Returns direct PNG generated by SHAP summary."""
    for folder in ["frontend/public", "public", "."]:
        p = os.path.join(folder, "xgboost_shap_summary.png")
        if os.path.exists(p):
            return FileResponse(p, media_type="image/png")
    engine.generate_plots("frontend/public")
    for folder in ["frontend/public", "public", "."]:
        p = os.path.join(folder, "xgboost_shap_summary.png")
        if os.path.exists(p):
            return FileResponse(p, media_type="image/png")
    raise HTTPException(status_code=404, detail="Chart not found")

@app.get("/api/plots/{filename}")
async def get_plot(filename: str):
    """Serves direct PNG plots requested by frontend at /api/plots/{filename}."""
    for folder in ["frontend/public", "public", "."]:
        p = os.path.join(folder, filename)
        if os.path.exists(p):
            return FileResponse(p, media_type="image/png")
    engine.generate_plots("frontend/public")
    for folder in ["frontend/public", "public", "."]:
        p = os.path.join(folder, filename)
        if os.path.exists(p):
            return FileResponse(p, media_type="image/png")
    raise HTTPException(status_code=404, detail=f"Plot {filename} not found")


@app.post("/api/copilot/chat")
async def copilot_chat(payload: CopilotChatRequest):
    # Use the injected environment variable, or the UI input box if provided
    active_client = or_client
    if payload.gemini_key:
        active_client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=payload.gemini_key,
        )
    elif not active_client and os.environ.get("OPENROUTER_API_KEY"):
        active_client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=os.environ.get("OPENROUTER_API_KEY"),
        )

    if not active_client:
        raise HTTPException(
            status_code=500,
            detail="OpenRouter API Key missing. Please set OPENROUTER_API_KEY in Render."
        )

    system_instruction = (
        "You are the senior EDA & hardware verification assistant inside ConfigIntel. "
        "You analyze simulation execution logs, PPA tradeoffs (latency, throughput, peak memory), "
        "and SHAP parameter risk attributions. Provide precise, actionable root-cause diagnoses, "
        "pointing out assertions, memory bottlenecks, and suggested configuration fixes."
    )

    try:
        response = active_client.chat.completions.create(
            model="nvidia/llama-3.1-nemotron-70b-instruct:free",
            messages=[
                {"role": "system", "content": system_instruction},
                {"role": "user", "content": payload.query}
            ],
            temperature=0.2,
        )
        return {"response": response.choices[0].message.content}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"OpenRouter API Error: {str(e)}")

@app.post("/api/copilot/summary")
async def copilot_summary(payload: CopilotSummaryRequest):
    active_client = or_client
    if payload.gemini_key:
        active_client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=payload.gemini_key,
        )
    elif not active_client and os.environ.get("OPENROUTER_API_KEY"):
        active_client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=os.environ.get("OPENROUTER_API_KEY"),
        )

    if not active_client:
        raise HTTPException(
            status_code=500,
            detail="OpenRouter API Key missing. Please set OPENROUTER_API_KEY in Render."
        )

    summary_prompt = (
        "Generate a structured Executive Verification Summary for pre-silicon validation leads. "
        "Include three distinct sections:\n"
        "1. **Root Cause Failure Profile** (common assertion triggers, fatal memory limits, Feature_Flag_X impact)\n"
        "2. **PPA Pareto Trade-Offs** (latency vs. memory usage and optimal throughput configs)\n"
        "3. **Recommended Testbench Actions** (concrete register adjustments, cache policy tuning, dynamic scheduling)\n"
        "Format cleanly with markdown bullet points."
    )

    try:
        response = active_client.chat.completions.create(
            model="nvidia/llama-3.1-nemotron-70b-instruct:free",
            messages=[
                {"role": "system", "content": "You are a verification engineering AI."},
                {"role": "user", "content": summary_prompt}
            ],
            temperature=0.2,
        )
        return {"summary": response.choices[0].message.content}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"OpenRouter API Error: {str(e)}")

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)