import os
import json
from typing import Optional, List, Dict, Any
from fastapi import FastAPI, UploadFile, File, HTTPException, Query
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import uvicorn
from google import genai
from google.genai import types

from analytics import ConfigAnalyticsEngine

app = FastAPI(title="ConfigIntel Observability API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize Gemini Client using the environment variable GEMINI_API_KEY
gemini_api_key = os.environ.get("GEMINI_API_KEY")
gemini_client = genai.Client(api_key=gemini_api_key) if gemini_api_key else None

class CopilotChatRequest(BaseModel):
    query: str
    mode: Optional[str] = "Gemini"
    gemini_key: Optional[str] = None

class CopilotSummaryRequest(BaseModel):
    query: Optional[str] = ""
    mode: Optional[str] = "Gemini"
    gemini_key: Optional[str] = None

# Backwards compatibility alias
ChatRequest = CopilotChatRequest

# Initialize engine with default datasets if available on disk
engine = ConfigAnalyticsEngine(
    csv_path="execution_data_master.csv", 
    jsonl_path="system_execution_logs.jsonl"
)

@app.get("/api/health")
async def health_check():
    """Health and status endpoint for frontend connection verification."""
    return {
        "status": "healthy",
        "data_loaded": not engine.df.empty,
        "total_runs": len(engine.df) if not engine.df.empty else 0,
        "columns": list(engine.df.columns)[:15] if not engine.df.empty else []
    }

@app.post("/api/ingest")
async def ingest_data(csv_file: UploadFile = File(...), jsonl_file: Optional[UploadFile] = File(None)):
    """Ingests fresh CSV telemetry and optional JSONL trace logs."""
    try:
        jsonl_lines = None
        if jsonl_file and jsonl_file.filename:
            content = await jsonl_file.read()
            jsonl_lines = content.splitlines()
            
        csv_file.file.seek(0)
        engine.update_from_memory(csv_file.file, jsonl_lines)
        return {
            "status": "success", 
            "total_runs": len(engine.df),
            "message": f"Successfully ingested {len(engine.df):,} execution runs."
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Ingestion failed: {str(e)}")

@app.get("/api/dashboard")
async def get_dashboard():
    """Returns aggregated KPIs, SHAP metrics, and Pareto frontier."""
    data = engine.get_dashboard_data()
    if not data:
        raise HTTPException(status_code=400, detail="No dataset loaded. Please ingest data.")
    return data

@app.get("/api/runs")
async def get_runs(
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    status: Optional[str] = Query(None),
    search: Optional[str] = Query(None)
):
    """Returns paginated and searchable runs for the live trace explorer."""
    return engine.get_runs_list(limit=limit, offset=offset, status=status, search=search)

@app.get("/api/run/{run_id}")
async def get_single_run(run_id: str):
    """Returns details and full trace events for a specific run ID."""
    details, logs = engine.get_run_details(run_id)
    if not details:
        raise HTTPException(status_code=404, detail=f"Run {run_id} not found.")
    return {"run_id": run_id, "details": details, "events": logs}

@app.get("/api/diff")
async def get_diff(pass_id: str, fail_id: str):
    """Calculates configuration and trace log diff between passing and failing executions."""
    if engine.df.empty:
        raise HTTPException(status_code=400, detail="No dataset loaded in engine.")
    params, log_p, log_f = engine.compute_run_diff(pass_id, fail_id, as_df=False)
    return {"params": params, "log_p": log_p, "log_f": log_f}

@app.get("/api/chart/xgboost")
async def get_xgboost_chart():
    """Returns direct PNG generated by XGBoost."""
    chart_path = "frontend/public/xgboost_importance.png"
    if not os.path.exists(chart_path):
        engine.generate_plots("frontend/public")
    if os.path.exists(chart_path):
        return FileResponse(chart_path, media_type="image/png")
    raise HTTPException(status_code=404, detail="Chart not found")

@app.get("/api/chart/shap")
async def get_shap_chart():
    """Returns direct PNG generated by SHAP summary."""
    chart_path = "frontend/public/xgboost_shap_summary.png"
    if not os.path.exists(chart_path):
        engine.generate_plots("frontend/public")
    if os.path.exists(chart_path):
        return FileResponse(chart_path, media_type="image/png")
    raise HTTPException(status_code=404, detail="Chart not found")


def _generate_with_fallback(client, contents, config=None):
    models_to_try = ["gemini-2.5-flash", "gemini-3.6-flash", "gemini-2.0-flash"]
    last_err = None
    for model_name in models_to_try:
        try:
            return client.models.generate_content(
                model=model_name,
                contents=contents,
                config=config,
            )
        except Exception as e:
            last_err = e
            err_str = str(e).lower()
            if "404" in err_str or "not_found" in err_str or "not available" in err_str:
                continue
            raise e
    raise last_err

@app.post("/api/copilot/chat")
async def copilot_chat(payload: CopilotChatRequest):
    # Select client: either request-level key or backend environment variable
    client = gemini_client
    if payload.gemini_key:
        client = genai.Client(api_key=payload.gemini_key)
    elif not client and os.environ.get("GEMINI_API_KEY"):
        client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

    if not client:
        raise HTTPException(
            status_code=500,
            detail="Gemini API Key is not configured on the server. Please set GEMINI_API_KEY in Render."
        )

    # Verification engineering context injected into every query
    system_instruction = (
        "You are the senior EDA & hardware verification assistant inside ConfigIntel. "
        "You analyze simulation execution logs, PPA tradeoffs (latency, throughput, peak memory), "
        "and SHAP parameter risk attributions. Provide precise, actionable root-cause diagnoses, "
        "pointing out assertions, memory bottlenecks, and suggested configuration fixes."
    )

    try:
        response = _generate_with_fallback(
            client=client,
            contents=payload.query,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                temperature=0.2,
            )
        )
        return {"response": response.text}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Gemini API Error: {str(e)}")

@app.post("/api/copilot/summary")
async def copilot_summary(payload: CopilotSummaryRequest):
    client = gemini_client
    if payload.gemini_key:
        client = genai.Client(api_key=payload.gemini_key)
    elif not client and os.environ.get("GEMINI_API_KEY"):
        client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

    if not client:
        raise HTTPException(
            status_code=500,
            detail="Gemini API Key is not configured on the server. Please set GEMINI_API_KEY in Render."
        )

    summary_prompt = (
        "Generate a structured Executive Verification Summary for pre-silicon validation leads. "
        "Include three distinct sections:\n"
        "1. **Root Cause Failure Profile** (common assertion triggers, fatal memory limits, Feature_Flag_X impact)\n"
        "2. **PPA Pareto Trade-Offs** (latency vs. memory usage and optimal throughput configs)\n"
        "3. **Recommended Testbench Actions** (concrete register adjustments, cache policy tuning, dynamic scheduling)\n"
        "Format cleanly with markdown bullet points."
    )

    try:
        response = _generate_with_fallback(
            client=client,
            contents=summary_prompt,
            config=types.GenerateContentConfig(temperature=0.2)
        )
        return {"summary": response.text}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Gemini API Error: {str(e)}")

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)